[package]
org = "crates"
name = "jsonpath"
version = "1.0.2"
distribution = "2201.2.0"
authors = ["Mohamed Sabthar (@MohamedSabthar)"]
repository = "https://github.com/MohamedSabthar/jsonpath"
license = ["Apache-2.0"]
keywords=["json", "json path", "json-transform", "json transform", "json to json", "json-convert", "json convert"]

[[platform.java11.dependency]]
path = "../native/build/libs/jsonpath-native-1.0.2-SNAPSHOT.jar"
groupId = "io.ballerina.xlibb"
artifactId = "jsonpath-native"
version = "1.0.2"

[[platform.java11.dependency]]
path = "./lib/json-path-2.7.0.jar"
groupId = "com.jayway.jsonpath"
artifactId = "json-path"
version = "2.7.0"

[[platform.java11.dependency]]
path = "./lib/json-smart-2.4.7.jar"
groupId = "net.minidev.json"
artifactId = "json-smart"
version = "2.4.7"

[[platform.java11.dependency]]
path = "./lib/accessors-smart-2.4.7.jar"
groupId = "net.minidev.json"
artifactId = "accessors-smart"
version = "2.4.7"
